_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 98
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 1
                - 12
            "12": 0.20.1
            "13": linux-x86_64
learning_rate:
    value: 2e-05
lora_dropout:
    value: 0.1
r:
    value: 4
