_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
max_length:
    value: 768
n_shots:
    value: 3
